"""users table

Revision ID: 1570c313815b
Revises: 
Create Date: 2020-12-03 18:38:31.698557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1570c313815b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BUFFER_PEOPLE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geolocation', sa.String(length=256), nullable=True),
    sa.Column('type_of_public', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('geolocation', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('VISITED_PLACES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.VARCHAR(length=256), nullable=True),
    sa.Column('lon', sa.VARCHAR(length=256), nullable=True),
    sa.Column('type_of_public', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('STATUS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result', sa.String(length=256), nullable=True),
    sa.Column('сontact_with_infected', sa.String(length=256), nullable=True),
    sa.Column('Symptoms', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STATUS')
    op.drop_table('VISITED_PLACES')
    op.drop_table('USERS')
    op.drop_table('BUFFER_PEOPLE')
    # ### end Alembic commands ###
